rm(list=ls())

library(Matching)
library(rgenoud)
library(foreign)

nsw <- read.dta("nsw.dta")

#logit to get the propensity scores
logit <- glm(treat ~ age + education + black
            + hispanic + married + nodegree
            + re75, family = binomial, data = nsw)

X  <- logit$fitted
Y  <- nsw$re78
Tr  <- nsw$treat

#genetic matching
GM <- GenMatch(Tr=Tr, X=X, estimand="ATT", M=4,
               pop.size=400, max.generations=20, wait.generations=20,
               replace = FALSE)

#matching using the weights generated by the GenMatch
match1 <- Match(Y=Y, Tr=Tr, X=X, M=4, estimand="ATT", replace = FALSE, Weight.matrix = GM)
summary(match1)

#matching balance
MB  <- MatchBalance(treat ~ age + education + black
                    + hispanic + married + nodegree
                    + re75, data=nsw, match.out=match1, nboots=10)
